name: Build README

on:
  push:
    paths:
      - "data/**"
      - "templates/**"
      - "scripts/**"
      - "requirements.txt"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate README
        run: python scripts/generate_readme.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain README.md)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: auto-generate README from JSON"
            git push
          else
            echo "No changes in README.md"
          fi
